List<String> images = [
  "assets/images/butterfly.jpg",
  "assets/images/edge.jpg",
  "assets/images/natural.jpg",
  "assets/images/beautiful_girl.jpg",
  "assets/images/natural.jpg",
  "assets/images/beautiful_girl.jpg",
  "assets/images/lake.jpg",
  "assets/images/forest.jpg",
  "assets/images/galaxysymmetric.jpg",
  "assets/images/night.jpg",
  "assets/images/lake.jpg",
  "assets/images/forest.jpg",
  "assets/images/galaxysymmetric.jpg",
  "assets/images/night.jpg",
  "assets/images/butterfly.jpg",
  "assets/images/edge.jpg",
  "assets/images/natural.jpg",
  "assets/images/beautiful_girl.jpg",
  "assets/images/natural.jpg",
  "assets/images/beautiful_girl.jpg",
  "assets/images/lake.jpg",
  "assets/images/forest.jpg",
  "assets/images/galaxysymmetric.jpg",
  "assets/images/night.jpg",
  "assets/images/lake.jpg",
  "assets/images/forest.jpg",
  "assets/images/galaxysymmetric.jpg",
  "assets/images/night.jpg",
  "assets/images/bluenight.jpg",
  "assets/images/galaxysymmetric.jpg",
];

List<String> title = [
  "Hounted Sky",
  "Fallen In Home",
  "The Dreaming Lunar",
  "Jack The Persian and the Black Castle",
  "The Black Post",
  "The Secret of Moon",
  "Feller King",
  "Magnificient Fairy",
  "Jack The Persian and the Black Castle",
  "The Black Post",
  "The Secret of Moon",
  "Feller King",
  "Sky Craper",
  "Velley Spark",
  "Hounted Sky",
  "Fallen In Home",
  "The Dreaming Lunar",
  "Jack The Persian and the Black Castle",
  "The Black Post",
  "The Secret of Moon",
  "Feller King",
  "Magnificient Fairy",
  "Jack The Persian and the Black Castle",
  "The Black Post",
  "The Secret of Moon",
  "Feller King",
  "Sky Craper",
  "Velley Spark",
  "Velley Spark",
  "Velley Spark"
];
